GET https://localhost:4300/api/contatos
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiZjlmZWEwMi0wMTg3LTQ5OWQtNmNmMi0wOGRjZjhjODJlMzMiLCJlbWFpbCI6InRlc3RlMkBnbWFpbC5jb20iLCJ1bmlxdWVfbmFtZSI6InRlc3RlMiIsImdpdmVuX25hbWUiOiJUZXN0ZTIiLCJuYmYiOjE3MzA2MDg1MjksImV4cCI6MTczMTA0MDUyOSwiaWF0IjoxNzMwNjA4NTI5LCJpc3MiOiJlQWdlbmRhIiwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdCJ9.uybWaNeYzKVIfARpJzZyq3T8WkYNPIMVT5omoStvElY
